
-- Tabela BANDS

CREATE TABLE BANDS (
		BAND_ID SERIAL PRIMARY KEY,
		NAME VARCHAR(255) NOT NULL,
		CITY VARCHAR(200),
		FACEBOOK_PAGE VARCHAR(255),
		YOUTUBE_PAGE VARCHAR(255),
		IG_PAGE VARCHAR(255),
		IMG_URL VARCHAR(500),
		WHATSAPP VARCHAR(20)
);
