
--Table User_Bands

CREATE TABLE USER_BANDS (
    USER_ID INT,
    BAND_ID INT,
    PRIMARY KEY (USER_ID, BAND_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    FOREIGN KEY (BAND_ID) REFERENCES BANDS (BAND_ID)
);
