-- Tabela USERS
CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    PHONE VARCHAR(15) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    GENDER VARCHAR(10),
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    BIRTH_DATE DATE,
    CITY VARCHAR(255),
    LANGUAGES VARCHAR(255),
    INSTRUMENTS VARCHAR(255),
    ADDRESS VARCHAR(255),
	MUSICAL_GENRE VARCHAR(255),
    MUSICAL_EXPERIENCE VARCHAR(255),
    BAND_ID INT,
    DESCRIPTION TEXT,
    YOUTUBE_LINK VARCHAR(255)
);



-- Tabela BANDS
CREATE TABLE BANDS (
    BAND_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    FACEBOOK_PAGE VARCHAR(255),
    YOUTUBE_PAGE VARCHAR(255),
    IG_PAGE VARCHAR(255),
    WHATSAPP VARCHAR(15)
);

-- Criação da tabela MATCHES por enquanto sem FK

CREATE TABLE MATCHES (
	MATCH_ID SERIAL PRIMARY KEY,
    ACTIVE_ID INT,
    IS_LIKE BOOLEAN,
	IS_BAND BOOLEAN,
    RECEPTIVE_ID INT
);
