
-- Tabela USERS

CREATE TABLE USERS (
		USER_ID SERIAL PRIMARY KEY,
		PHONE VARCHAR(15) NOT NULL,
		NAME VARCHAR(255) NOT NULL,
		GENDER VARCHAR(10),
		EMAIL VARCHAR(255) UNIQUE NOT NULL,
		PASSWORD VARCHAR(255) NOT NULL,
		BIRTH_DATE DATE,
		CITY VARCHAR(255),
		LANGUAGES VARCHAR(255),
		INSTRUMENTS VARCHAR(255),
		ADDRESS VARCHAR(255),
		MUSICAL_GENRE VARCHAR(255),
		MUSICAL_EXPERIENCE VARCHAR(255),
		DESCRIPTION TEXT,
		IMG_URL VARCHAR(500),
		WHATSAPP VARCHAR(20),
		YOUTUBE_LINK VARCHAR(255)
);
